### ISSUE TITLE
[LevelOne] Fix the overlap with quiz items and the footer

### ISSUE THREAD

**Issue by MargaretThomas** [DevMingler/logo-matcher-game#2]
When reaching the bottom of the screen, on mobile, the last input is cutoff. Increase margins where possible to ensure visibility of all quiz items and footer.

**Comment by MargaretThomas** [comment]
Overlap also occurs on desktop

**Comment by Phil94comp** [comment]
I submitted a pull request for this issue. Please let me know if you like the changes.

**Comment by MargaretThomas** [comment]
I like the changes, thanks Phillip 😄
