### ISSUE TITLE
[LevelTwo] Add 20 logos for Level 20

### ISSUE THREAD

**Issue by MargaretThomas** [DevMingler/logo-matcher-game#5]
Use all 10 logos from Level One. Find 10 additional logos and import them into this project.
Ensure consistent naming of logos.

**Comment by Phil94comp** [comment]
I have come up with 12 logos and just need some guidance as to where to get the fair use images. If possible, I would like to use the same source as the original 10 logos already in the project.

**Comment by MargaretThomas** [comment]
You can use this Figma file - https://www.figma.com/community/file/1161721251517347938

It has 800+ logos. You can select the logos you want and export them.

**Comment by Phil94comp** [comment]
I just submitted a pull request. Please let me know if you like the logos I picked out.

**Comment by MargaretThomas** [comment]
Good choices. I've approved the pull request.
